### PR TITLE
fix: generic type error of `RouteShorthandMethod`

### LINKED ISSUE #280: fix a typescript generic type error
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

x

### Plugin version

x

### Node.js version

x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

x

### Description

I'm trying to practice a tutorial of `Platformatic`，and in this template, `compilerOptions.skipLibCheck` is not on. so it exposed a problem of @fastify/websocket。
image
and typescript should output:
`Generic type 'RouteShorthandMethod<RawServer, RawRequest, RawReply, TypeProvider>' requires between 0 and 4 type arguments.`

i think the `Logger` generic parameter is useless and should be removed.

### Steps to Reproduce

https://docs.platformatic.dev/docs/getting-started/movie-quotes-app-tutorial

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by XHFkindergarten**
closes #280 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by XHFkindergarten** [comment]
#280

**Review by mcollina — COMMENTED** [review]
Could you add a test for this type change? We use `tsd`.

**Comment by XHFkindergarten** [comment]
> Could you add a test for this type change? We use `tsd`.

done，I think a default type check is enough.

**Review by airhorns — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
