### PR TITLE
Update for Fastify v5

### PR DESCRIPTION
**Pull request by synapse**
Ref: https://github.com/fastify/fastify/issues/5116

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by gurgunday** [comment]
Ok, will start merging now, but just for consistency, I've so far kept the .taprc files and haven't moved tap options to package.json as so far we've preferred explicit config files

So it would be great if you could keep `.taprc`, thanks

https://github.com/fastify/fastify-cookie/blob/next/.taprc
https://github.com/fastify/fastify-rate-limit/blob/next/.taprc

**Review by gurgunday — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
CI is failing

**Comment by gurgunday** [comment]
Hey @synapse sorry for this, but master had a breaking change and it requires some refactoring, do you have time to take a look?

**Review by gurgunday — APPROVED** [review]
lgtm, thank you!

**Review by gurgunday — APPROVED** [review]

**Pull request merged**
