### PR TITLE
fix(types): websocketPlugin is not an existing variable

### PR DESCRIPTION
**Pull request by Yovach**
This PR fixes a mistake in types.
The named exports `websocketPlugin` doesn't exist in the code and you can't use it 

Until this PR is merged, you can do the following : 

fastify-websocket.d.ts
```typescript 
import type websocketPlugin from "@fastify/websocket";

declare module "@fastify/websocket" {
  export const fastifyWebsocket: typeof websocketPlugin;
}
```

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
image

Shame!

thank you.

**Comment by mcollina** [comment]
Can you add a test using tsd to prevent this for regressing?

**Comment by Yovach** [comment]
> Can you add a test using tsd to prevent this for regressing?

I added a test for named-import but tests seems broken in fastify@4.24.0

**Review by mcollina — COMMENTED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
Other typings fails are unrelated to this PR.

**Pull request merged**
